global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.host.internal:9090']
  - job_name: 'transaction-note-app'
    metrics_path: '/api/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.host.internal:5000']
  - job_name: 'transaction-note-auth-service-app'
    metrics_path: '/api/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.host.internal:5004']
