# Default values for api-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
services:
  environment: local
  image: neltoby/microservice:v1
  namespace: default
  externalSecret:
    name: transfernow-secret
    backendType: vault
    secretTarget: secrets-service
    vault:
      path: secret/transfernow/services
      role: transfernow
      mountPoint: kubernetes
    secret:
      broker: broker
      auth_mongo_url: authmongourl
      identity_mongo_url: identitymongourl
      notification_mongo_url: notificationmongourl
      jwt_secret: jwtsecret
      redis_password: redispassword
      redis_host: redishost
      redis_port: redisport
      mailtrap_host: mailtraphost
      mailtrap_port: mailtrapport
      mailtrap_auth_user: mailtrapauthuser
      mailtrap_auth_pass: mailtrapauthpass
      authdb_user: authdbuser
      authdb_password: authdbpassword
      identitydb_user: identitydbuser
      identitydb_password: identitydbpassword
      notificationdb_user: notificationdbuser
      notificationdb_password: notificationdbpassword

  # api-gateway microservice definations
  apigateway:
    name: api-gateway

    # api-gateway k8s configmap helm values
    configmap:
      name: transfernowconfigmap

    # api-gateway k8s service helm values
    service:
      name: api-gateway-service
      port: '5000'

    # api-gateway k8s ingress
    ingress:
      name: api-gateway-ingress

    # api-gateway kubernetes deployment helm values
    deployment:
      name: api-gateway-deployment
      replicas: 2
      containerPort: '5000'
      containerName: api-gateway

    # api-gateway vault secret
    secrets:
      - jwt_secret
      - broker

  # auth microservice defination
  auth:
    name: auth

    # auth k8s service helm values
    service:
      name: auth-service
      port: '5004'

    # ath k8s deployment helm values
    deployment:
      name: auth-deployment
      replicas: 2
      containerPort: '5004'
      containerName: auth

    # auth vault secret
    secrets:
      - jwt_secret
      - broker
      - auth_mongo_url

  # identity microservice definations
  identity:
    name: identity

    # identity k8s service helm values
    service:
      name: identity-service
      port: '5002'

    # identity k8s deployment helm values
    deployment:
      name: identity-deployment
      replicas: 2
      containerPort: '5002'
      containerName: identity

    # identity vault secrets
    secrets:
      - jwt_secret
      - broker
      - identity_mongo_url
      - redis_host
      - redis_password
      - redis_port

  # notification microservice definitions
  notification:
    name: notification

    # notification k8s service helm values
    service:
      name: notification-service
      port: '5005'

    # notification k8s deployment helm values
    deployment:
      name: notification-deployment
      replicas: 2
      containerPort: '5005'
      containerName: notification
