{{- with .Values.services }}
# SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  {{- if eq .environment "local" }}
  provider:
    vault:
      server: "http://vault:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "transfernow"
          serviceAccountRef:
            name: transfernow
  {{ else if eq .environment "dev" }}
  provider:
    azurekv:
      authType: ManagedIdentity
      # identityId: 5f9add98-6f07-41b8-8430-00ad9a27c9d9
      vaultUrl: "https://transfernow-vault.vault.azure.net"
  {{- end }}
---
# External Secret
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
{{- with .externalSecret }}
metadata:
  name: {{ .name}}
{{ include "service-chart.v0.namespace" (list $ $.Values.services) | indent 2}}
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ .secretTarget }}
    {{- if ne $.Values.services.environment "local" }}
    creationPolicy: Owner
    {{- end }}
  data:
    {{- $path := .vault.path -}}
    {{- $env := $.Values.services.environment -}}
    {{- range $key, $val := .secret}}
    - secretKey: {{ upper $key}}
      remoteRef:
        key: {{ if eq $env "local" }}{{ $path }}{{ else }}{{ $val}}{{ end }}
        {{- if eq $env "local" }}
        property: {{ $val}}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
---

# # PullImageSecret
# {{- if .Values.services.development }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: myregistrykey
# data:
#   .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiCn0="
# type: kubernetes.io/dockerconfigjson
# {{- end }}
