# SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "transfernow"
          serviceAccountRef:
            name: transfernow
---

# External Secret
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
{{- with .Values.services.externalSecret }}
metadata:
  name: {{ .name}}
{{ include "service-chart.v0.namespace" (list $ $.Values.services) | indent 2}}
spec:
  secretStoreRef:
     name: vault-backend
     kind: SecretStore
  target:
     name: {{ .secretTarget }}
  data:
    {{- $path := .vault.path -}}
    {{- range $key, $val := .secret}}
    - secretKey: {{ upper $key}}
      remoteRef:
        key: {{ $path }}
        property: {{ $val}}
    {{- end }}
{{- end }}
---

# # PullImageSecret
# {{- if .Values.services.development }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: myregistrykey
# data:
#   .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiCn0="
# type: kubernetes.io/dockerconfigjson
# {{- end }}
