{{- if .Values.services.development -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auth-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain 
volumeBindingMode: Immediate
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: identity-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain 
volumeBindingMode: Immediate
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: notification-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain 
volumeBindingMode: Immediate
{{- end -}}