# apiVersion: v1
# kind: Namespace
# metadata:
#   {{- with .Values.services }}
#   name: {{ .namespace | replace " " " -"}}{{ if .development }}-dev{{ end }}
#   {{- end }}
# ---
{{- if eq .Values.services.environment "local" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.services }}
  name: {{ cat $.Release.Name .apigateway.ingress.name | replace " " "-" }}
  {{- end }}
{{ include "service-chart.v0.namespace" (list $ .Values.services) | indent 2 }}
spec:
  rules:
    - host: transfernow.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              {{- with .Values.services.apigateway.service }}
              service: 
                name: {{ cat $.Release.Name .name | replace " " "-" }}
                port: 
                  number: {{ .port }}
              {{- end }}
    - host: auth.transfernow.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              {{- with .Values.services.auth.service }}
              service: 
                name: {{ cat $.Release.Name .name | replace " " "-" }}
                port: 
                  number: {{ .port }}
              {{- end }}
    - host: identity.transfernow.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              {{- with .Values.services.identity.service }}
              service: 
                name: {{ cat $.Release.Name .name | replace " " "-" }}
                port: 
                  number: {{ .port }}
              {{- end }}
    - host: notification.transfernow.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              {{- with .Values.services.notification.service }}
              service: 
                name: {{ cat $.Release.Name .name | replace " " "-" }}
                port: 
                  number: {{ .port }}
              {{- end }}
{{- end -}}
---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.services.apigateway.service }}
  name: {{ cat $.Release.Name .name | replace " " "-" }}
  {{- end }}
  {{- if eq .Values.services.environment "dev" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  {{- end }}
{{ include "service-chart.v0.namespace" (list $ .Values.services) | indent 2 }}
spec:
  {{- if eq .Values.services.environment "dev" }}
  type: LoadBalancer
  {{- end }}
  selector:
{{ include "service-chart.v0.selector" .Values.services.apigateway | indent 4}}
  ports:
  {{- with .Values.services.apigateway }}
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: {{ .deployment.containerPort }}
  {{- end }}
---
# ConfigMap
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ cat $.Release.Name .Values.services.apigateway.configmap.name | replace " " "-" }}
{{ include "service-chart.v0.namespace" (list $ .Values.services) | indent 2 }}
data:
  node-env: {{ if eq .Values.services.environment "local" }} development {{ else }} production {{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.services.apigateway.deployment }}
  name: {{cat $.Release.Name .name | replace " " "-" }}
  {{- end }}
{{ include "service-chart.v0.namespace" (list $ .Values.services) | indent 2 }}
  labels:
{{ include "service-chart.v0.selector" .Values.services.apigateway | indent 4}}
spec:
  replicas: {{ .Values.services.apigateway.deployment.replicas }}
{{ include "service-chart.v0.strategy" . | indent 2}}
  selector:
    matchLabels:
{{ include "service-chart.v0.selector" .Values.services.apigateway | indent 6}}
  template:
    metadata:
      labels:
{{ include "service-chart.v0.selector" .Values.services.apigateway | indent 8 }}
    spec:
      serviceAccountName: vault
      volumes:
        - name: api-gateway-config
          configMap:
            name: {{ cat $.Release.Name .Values.services.apigateway.configmap.name | replace " " "-" }}
{{ include "service-chart.v0.imagePullSecret" . | indent 6 }}
      containers:
        {{- with .Values.services.apigateway.deployment }}
        - name: {{ .containerName }}
          image: {{ $.Values.services.image }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: {{ .containerPort }}
          command: ["/bin/sh", "-c"]
          args: ["npx nx run api-gateway-service:serve"]
          env:
            - name: PORT
              value: {{ squote .containerPort }}
        {{- end }}
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ cat $.Release.Name .Values.services.apigateway.configmap.name | replace " " "-" }}
                  key: node-env
{{- include "service-chart.v0.ext-secrets" (list $ .Values.services.apigateway) | indent 12 -}}