# ConfigMap
kind: ConfigMap
apiVersion: v1
metadata:
  name: transaction-config
data:
  broker: kafka:9092
  node-env: development
  auth-mongo-url: mongodb://root:root@auth-mongodb:27017/
  identity-mongo-url: mongodb://root:root@identity-mongodb:27017/
  notification-mongo-url: mongodb://root:root@notification-mongodb:27017/
  redis-host: redis
  mailtrap-host: sandbox.smtp.mailtrap.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      volumes:
        - name: api-gateway-config
          configMap:
            name: transaction-config
      containers:
        - name: api-gateway
          image: transaction-note-api-gateway
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: transaction-config
                  key: node-env
            - name: BROKER
              valueFrom:
                configMapKeyRef:
                  name: transaction-config
                  key: broker