apiVersion: v1
kind: Service
metadata:
  {{- with .Values.services.auth.service }}
  name: {{ cat $.Release.Name .name | replace " " "-" }}
  {{- end }}
{{ include "service-chart.v0.namespace" (list $ .Values.services) | indent 2 }}
spec:
  selector:
{{ include "service-chart.v0.selector" .Values.services.auth | indent 4 }}
  ports:
    - protocol: TCP
      {{- with .Values.services.auth }}
      port: {{ .service.port }}
      targetPort: {{ .deployment.containerPort }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.services.auth.deployment }}
  name: {{ cat $.Release.Name .name | replace " " "-" }}
  {{- end }}
{{ include "service-chart.v0.namespace" (list $ .Values.services) | indent 2}}
  labels:
{{ include "service-chart.v0.selector" .Values.services.auth | indent 4 }}
spec:
  replicas: {{ .Values.services.auth.deployment.replicas }}
{{ include "service-chart.v0.strategy" . | indent 2}}
  selector:
    matchLabels:
{{ include "service-chart.v0.selector" .Values.services.auth | indent 6 }}
  template:
    metadata:
      labels:
{{ include "service-chart.v0.selector" .Values.services.auth | indent 8 }}
    spec:
      serviceAccountName: vault
      volumes:
        - name: auth-config
          configMap:
            name: {{ cat $.Release.Name .Values.services.apigateway.configmap.name | replace " " "-" }}
{{ include "service-chart.v0.imagePullSecret" . | indent 6 }}
      containers:
        {{- with .Values.services.auth.deployment }}
        - name: {{ .containerName }}
          image: {{ $.Values.services.image }}
          ports:
            - containerPort: {{ .containerPort }}
          command: ["/bin/sh", "-c"]
          args: ["npx nx run auth-service:serve"]
          env:
            - name: PORT
              value: {{ squote .containerPort }}
        {{- end }}
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ cat $.Release.Name .Values.services.apigateway.configmap.name | replace " " "-" }}
                  key: node-env
{{- include "service-chart.v0.ext-secrets" (list $ .Values.services.auth) | indent 12 -}}